# Generated by Django 3.2.19 on 2023-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('topic', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
